### ISSUE TITLE
Error: Missing option '--stack-name'

### ISSUE THREAD

**Issue by GABAnich** [TractorZoom/sam-cli-action#19]
I want to deploy my changes but got the error

```
Install aws-sam-cli latest
Successful install aws-sam-cli latest
cd ./
Run sam deploy --parameter-overrides TelegramToken=***
Usage: sam deploy [OPTIONS]
Try 'sam deploy --help' for help.

Error: Missing option '--stack-name', 'sam deploy --guided' can be used to provide and save needed parameters for future deploys.
```

stack-name is defined in `samconfig.toml`
Would be good, if `sam-cli-action` can take this param from that file

**Comment by GABAnich** [comment]
samconfig.toml

```toml
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "locash"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1h8e2lfoc21uu"
s3_prefix = "locash"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
```
