### ISSUE TITLE
Github Package Registry token doesn't work

### ISSUE THREAD

**Issue by felipe-silvestre-morais** [TractorZoom/sam-cli-action#23]
**Describe the bug**
github_package_registry_token action doesn't work.
I created a personal token and set it to github_package_registry_token. But once my workflow runs I am getting error 401.
That is part of my yml file:

```
steps:
    - name: checkout  
      uses: actions/checkout@master        
    - name: sam build
      uses: TractorZoom/sam-cli-action@master       
      with:
        github_package_registry_token: ${{ secrets.GH_TOKEN }}
        sam_command: 'build -t template.yaml'
```

**Expected behavior**
Setting github_package_registry_token should work.

**Additional context**
Reading the [entrypoint.sh](https://github.com/TractorZoom/sam-cli-action/blob/master/entrypoint.sh#L33) file, the IF doesn't seem right since it is testing if the parameter is empty.
