### ISSUE TITLE
Error: PythonPipBuilder:Validation

### ISSUE THREAD

**Issue by MatteoGioioso** [TractorZoom/sam-cli-action#5]
**Describe the bug**
Hello there,

Not really sure this is a bug on your side or the `actions/setup-python@v1` package. Anyway I cannot run the build as the sam-cli cannot locate the python runtime. 
This is the error I got:
```
Error: PythonPipBuilder:Validation - Binary validation failed for python, searched for python in following locations  : ['/usr/local/bin/python'] which did not satisfy constraints for runtime: python3.6. Do you have python for runtime: python3.6 on your PATH?
```

**To Reproduce**
This is my workflow.yaml file

```
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        ...

      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: build
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: build --build-dir mypath/build/  --template mypath/template.yaml
```

**Expected behavior**
Should local the python runtime

Thanks
