### ISSUE TITLE
No module named 'samcli'

### ISSUE THREAD

**Issue by z0ph** [TractorZoom/sam-cli-action#6]
Hello,

**Describe the bug**

```
Install aws-sam-cli latest
Successful install aws-sam-cli latest
Run sam build
Traceback (most recent call last):
  File "/bin/sam", line 5, in <module>
    from samcli.cli.main import cli
ModuleNotFoundError: No module named 'samcli'
```

Is this a known issue?

I saw a very similar approach and same issue using: https://github.com/youyo/aws-sam-action

**Comment by cody-hoffman** [comment]
@z0ph please provide information on how you came upon this bug, steps to reproduce, etc. We have this `sam-cli-action` running any many production pipelines at Tractor Zoom with no issues.

**Comment by z0ph** [comment]
Hello @cody-hoffman 

Thanks for the feedback,

Actually, I'm using this GH Actions workflow:

```
name: "deploy pipeline"

on: 
  push:
    branches:
    - master

jobs:
  aws_sam:
    runs-on: ubuntu-latest
    steps:
      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-to-assume: xxx-admin
          role-duration-seconds: 1200
          role-session-name: GH-Actions

      - name: Checkout
        uses: actions/checkout@master

      - name: Test credentials - whoami
        run: |
          aws sts get-caller-identity

      - name: sam build
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "build"
```

**Comment by cody-hoffman** [comment]
Do you have the env variables set on the sam build step? 

```yaml
- name: sam build
  uses: TractorZoom/sam-cli-action@master
  with: 
    sam_command: build
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.REGION }}
```

**Comment by z0ph** [comment]
No, I'm using the "Assume Role" step to get AWS credentials for this runner.

I've tried to set env:

```
Install aws-sam-cli latest
Successful install aws-sam-cli latest
Run sam build
Traceback (most recent call last):
  File "/bin/sam", line 5, in <module>
    from samcli.cli.main import cli
ModuleNotFoundError: No module named 'samcli'
```

Same error. Are you using same: `runs-on: ubuntu-latest` ?

**Comment by cody-hoffman** [comment]
Yes we are. I'm not familiar with how the Assume Role step works, as a debug step have you verified that passing your credentials as env variables also fails similarly?

**Comment by cody-hoffman** [comment]
What version of python are you on? This is currently only supporting 3.8 as we primarily develop in Node

**Comment by z0ph** [comment]
> Yes we are. I'm not familiar with how the Assume Role step works, as a debug step have you verified that passing your credentials as env variables also fails similarly?

Yes same error using: 

```
name: "deploy pipeline"

on: 
  push:
    branches:
    - master

jobs:
  aws_sam:
    runs-on: ubuntu-latest
    steps:
      # - name: Assume Role
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: eu-west-1
      #     role-to-assume: zoph-admin
      #     role-duration-seconds: 1200
      #     role-session-name: GH-Actions

      - name: Checkout
        uses: actions/checkout@master

      # - name: Test credentials - whoami
      #   run: |
      #     aws sts get-caller-identity

      - name: sam build
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "build"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.REGION }}
```
